package no.runsafe.cheeves;

public enum Achievements
{
	GLADIATOR,
	PIMP,
	EMERALD_CITY,
	TUNNEL,
	DEFENSE_OF_THE_KINGDOM,
	PVP_TOURNAMENT_JUNE,
	SERVER_FIRST_ENDER_DRAGON,
	MY_PRECIOUS,
	WIZARD_HEAD,
	SHIELDWALL,
	SPONGE,
	WICKED_SICK,
	MERCILESS_GLADIATOR,
	FLESH_WOUND,
	KNUCKLE_SANDWICH,
	CHEERIOS,
	WHAT_ARE_THE_ODDS,
	SEWAGE_SURVIVOR,
	LIGHTNING_STRIKES_TWICE,
	I_MADE_THAT,
	SUPREME_ARCHITECT,
	MY_BRAIN_HURTS,
	SERVER_FIRST_MY_BRAIN_HURTS
}
