name: Cheeves
main: no.runsafe.cheeves.Mergic
version: 1.0.@BUILD@
author: Kruithne
description: Achievements!
depend: [RunsafeInventories]
commands:
  achievements:
    description: Achievement related commands
    aliases: [achievement, ach, achieve]
  awardach:
    description: Awards an achievement to a player
